import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
opacity = 0.9

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"
